<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="UTF-8">
    <title>Practical machine learning by dkshort</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="stylesheets/normalize.css" media="screen">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css" media="screen">
    <link rel="stylesheet" type="text/css" href="stylesheets/github-light.css" media="screen">
  </head>
  <body>
    <section class="page-header">
      <h1 class="project-name">Practical machine learning</h1>
      <h2 class="project-tagline">Assignment for Practical Machine Learning</h2>
      <a href="https://github.com/dkshort/Practical_Machine_Learning" class="btn">View on GitHub</a>
      <a href="https://github.com/dkshort/Practical_Machine_Learning/zipball/master" class="btn">Download .zip</a>
      <a href="https://github.com/dkshort/Practical_Machine_Learning/tarball/master" class="btn">Download .tar.gz</a>
    </section>

    <section class="main-content">
      <h1>
<a id="pml-assignment" class="anchor" href="#pml-assignment" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a>PML Assignment</h1>

<h4>
<a id="david-short" class="anchor" href="#david-short" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a><em>David Short</em>
</h4>

<h4>
<a id="16-july-2016" class="anchor" href="#16-july-2016" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a><em>16 July 2016</em>
</h4>

<p></p>

<div id="introduction">
<h2>
<a id="introduction" class="anchor" href="#introduction" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a>Introduction</h2>
<p>The task for this assignment is to create a model capable of predicting whether a person is using a piece of exercise equipment correctly, based on data recorded by sensors worn on the body. In this case the exercise equipment was a dumbbell used to perform a biceps curl, with sensors located on the belt, upper arm, forearm and on the dumbbell itself.</p>
<p>The data used relates to the paper“Qualitative Activity Recognition of Weight Lifting Exercises” by Velloso, E.; Bulling, A.; Gellersen, H.; Ugulino, W.; Fuks, H.</p>
<p>More information about this paper can be found at <a href="http://groupware.les.inf.puc-rio.br/har#ixzz4EcRDpAYb">http://groupware.les.inf.puc-rio.br/har#ixzz4EcRDpAYb</a>.</p>
</div>

<div id="data-download">
<h2>
<a id="data-download" class="anchor" href="#data-download" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a>Data Download</h2>
<p>The training data set was downloaded from <a href="https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv">https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv</a>.</p>
<p>A testing data set was also downloaded from <a href="https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv">https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv</a>.</p>
</div>

<div id="library">
<h2>
<a id="library" class="anchor" href="#library" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a>Library</h2>
<p>The caret library is used to model data within this assignment. The rattle library is used to show the decision tree model.</p>
<pre><code>library(caret)
library(rattle)</code></pre>
</div>

<div id="data-selection">
<h2>
<a id="data-selection" class="anchor" href="#data-selection" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a>Data Selection</h2>
<p>Exploratory analysis revealed not all columns within the data set were fully populated, with large numbers of NA and !DIV/0 values. As these sparsely populated columns would produce an unreliable model, these were excluded.</p>
<p>Also excluded were columns that did not appear to be likely to influence the prediction, such as participant and date/time information.</p>
<p>This left us with 52 measurement columns, along with the classe column to be predicted.</p>
<p>The classe column has 5 possible values:</p>
<ul>
<li>A - exercise performed correctly;</li>
<li>B - elbows thrown to the front;</li>
<li>C - dumbbell lifted only halfway;</li>
<li>D - dumbbell lowered only halfway; and</li>
<li>E - hips thrown to the front.</li>
</ul>
<p>The data was segmented into a training set (70%) and a testing set (30%) for model development.</p>
<pre><code>setwd("~/R/PML Assignment")
trainingFull &lt;- read.csv("pml-training.csv",stringsAsFactors = FALSE)
trainingFull$classe &lt;- as.factor(trainingFull$classe)

beltCols &lt;- c("roll_belt","pitch_belt","yaw_belt","total_accel_belt","gyros_belt_x","gyros_belt_y","gyros_belt_z","accel_belt_x","accel_belt_y","accel_belt_z","magnet_belt_x","magnet_belt_y","magnet_belt_z")

armCols &lt;- c("roll_arm","pitch_arm","yaw_arm","total_accel_arm","gyros_arm_x","gyros_arm_y","gyros_arm_z","accel_arm_x","accel_arm_y","accel_arm_z","magnet_arm_x","magnet_arm_y","magnet_arm_z")

dumbbellCols &lt;- c("roll_dumbbell","pitch_dumbbell","yaw_dumbbell","total_accel_dumbbell","gyros_dumbbell_x","gyros_dumbbell_y","gyros_dumbbell_z","accel_dumbbell_x","accel_dumbbell_y","accel_dumbbell_z","magnet_dumbbell_x","magnet_dumbbell_y","magnet_dumbbell_z")

forearmCols &lt;- c("roll_forearm","pitch_forearm","yaw_forearm","total_accel_forearm","gyros_forearm_x","gyros_forearm_y","gyros_forearm_z","accel_forearm_x","accel_forearm_y","accel_forearm_z","magnet_forearm_x","magnet_forearm_y","magnet_forearm_z")

colsToInclude &lt;- c("classe",beltCols,armCols,dumbbellCols,forearmCols)

trainingSubset &lt;- trainingFull[colsToInclude]

set.seed(710)
inTrain &lt;- createDataPartition(trainingSubset$classe,p=0.7,list=FALSE)
trainingSet &lt;- trainingSubset[inTrain,]
testingSet &lt;- trainingSubset[-inTrain,]</code></pre>
</div>

<div id="fitting-models">
<h2>
<a id="fitting-models" class="anchor" href="#fitting-models" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a>Fitting Models</h2>
<div id="decision-tree">
<h3>
<a id="decision-tree" class="anchor" href="#decision-tree" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a>Decision Tree</h3>
<p>A decision tree model was fitted to the data.</p>
<pre><code>set.seed(1812)
treeFit &lt;- train(classe~., data=trainingSet, method="rpart")</code></pre>
<pre><code>treePred &lt;- predict(treeFit, newdata=testingSet)
treeMatrix &lt;- confusionMatrix(testingSet$classe, treePred)

treeMatrix$table</code></pre>
<pre><code>##           Reference
## Prediction    A    B    C    D    E
##          A 1501   24  124    0   25
##          B  450  384  305    0    0
##          C  467   41  518    0    0
##          D  437  165  362    0    0
##          E  162  142  281    0  497</code></pre>
<pre><code>treeMatrix$overall[1]</code></pre>
<pre><code>##  Accuracy 
## 0.4927782</code></pre>
<pre><code>treeAccuracyPercent &lt;- sprintf("%2.2f",treeMatrix$overall[1]*100)</code></pre>
<p>This indicated an accuracy of 49.28%. This indicates that the model is not particularly useful for predicting the correct conduct of this exercise.</p>
</div>

<div id="random-forest">
<h3>
<a id="random-forest" class="anchor" href="#random-forest" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a>Random Forest</h3>
<p>A random forest model was then fitted to the data. Cross validation method was used as somewhat more efficient than resampling.</p>
<pre><code>set.seed(1602)
rfFitControl &lt;- trainControl(method="cv",number=10)
rfFit &lt;- train(classe~.,data=trainingSet,model="rf",trControl=rfFitControl, importance=TRUE)

varImpPlot(rfFit$finalModel)</code></pre>
<p><img width="672"></p>
<pre><code>rfPred &lt;- predict(rfFit, newdata = testingSet)
rfMatrix &lt;- confusionMatrix(testingSet$classe, rfPred)

rfMatrix$table</code></pre>
<pre><code>##           Reference
## Prediction    A    B    C    D    E
##          A 1669    3    1    0    1
##          B   12 1126    1    0    0
##          C    0    5 1020    1    0
##          D    0    0    9  955    0
##          E    0    1    1    5 1075</code></pre>
<pre><code>rfMatrix$overall[1]</code></pre>
<pre><code>##  Accuracy 
## 0.9932031</code></pre>
<pre><code>rfAccuracyPercent &lt;- sprintf("%2.2f",rfMatrix$overall[1]*100)</code></pre>
<p>This indicated an accuracy of 99.32%. This therefore appears to be a good model in predicting incorrect use of the dumbbell in this exercise.</p>
<p>We therefore utilised this model to supply the answers for the prediction quiz data.</p>
<pre><code>testingFull &lt;- read.csv("pml-testing.csv",stringsAsFactors = FALSE)
finalPred &lt;- predict(rfFit, newdata = testingFull)
finalPred &lt;- data.frame(finalPred)
finalPred</code></pre>
<pre><code>##    finalPred
## 1          B
## 2          A
## 3          B
## 4          A
## 5          A
## 6          E
## 7          D
## 8          B
## 9          A
## 10         A
## 11         B
## 12         C
## 13         B
## 14         A
## 15         E
## 16         E
## 17         A
## 18         B
## 19         B
## 20         B</code></pre>
</div>

<p></p>
</div>

<div id="conclustion">
<h2>
<a id="conclustion" class="anchor" href="#conclustion" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a>Conclustion</h2>
<p>The random Forest model appears to provide an accurate model that could be used to predict whether this exercise has been performed correctly, and if not, which error has occurred.</p>
</div>

<p></p>

      <footer class="site-footer">
        <span class="site-footer-owner"><a href="https://github.com/dkshort/Practical_Machine_Learning">Practical machine learning</a> is maintained by <a href="https://github.com/dkshort">dkshort</a>.</span>

        <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using the <a href="https://github.com/jasonlong/cayman-theme">Cayman theme</a> by <a href="https://twitter.com/jasonlong">Jason Long</a>.</span>
      </footer>

    </section>

  
  </body>
</html>
